version: 2
jobs:
  build:
    working_directory: ubuntu/python/
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=20.10.py3.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=ubuntu' >> $BASH_ENV 
            echo 'export DOCKER_LOGIN=singharunk' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t singharunk/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push singharunk/$IMAGE_NAME:$TAG
