name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- netshoot

variables:
- group: BUILD-ARG
- name: tag
  value: '$(Build.BuildId)'

# resources:
#   repositories:
#   - repository: DockerFilesForUse
#     type: github
#     endpoint: github.com_arunksingh16
#     name: github.com_arunksingh16/DockerFilesForUse
#     ref: netshoot

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Login to Registry
      inputs:
        containerRegistry: 'dockerhub'
        command: 'login'
        addPipelineData: false
    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerreg)'
        repository: 'singharunk/netshoot'
        command: 'push'
        tags: |
          $(tag)
          latest
        addPipelineData: false
    - task: Docker@2
      displayName: Logout to  Registry
      inputs:
        containerRegistry: $(dockerreg)
        command: 'logout'
        addPipelineData: false
