trigger:
- netshoot

resources:
  repositories:
  - repository: DockerFilesForUse
    type: github
    endpoint: github.com_arunksingh16
    name: github.com_arunksingh16/DockerFilesForUse
    ref: netshoot

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - checkout: DockerFilesForUse
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
