name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- ubuntu/light

variables:
- group: BUILD-ARG
- name: tag
  value: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Login to Registry
      inputs:
        containerRegistry: 'dockerhub'
        command: 'login'
        addPipelineData: false
    - task: Docker@2
      displayName: Build image
      inputs:
        containerRegistry: '$(dockerreg)'
        repository: 'singharunk/ubuntu'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: light
        addPipelineData: false
    - task: Docker@2
      displayName: Logout to  Registry
      inputs:
        containerRegistry: $(dockerreg)
        command: 'logout'
        addPipelineData: false
